== Contributing to NimGL

We are really glad you're reading this, because we need volunteer developers to help this project come to fruition. 👏

=== Code of Conduct

This project and everyone participating in it is governed by the link:CODE_OF_CONDUCT.adoc[Code of Conduct]. By
participating, you are expected to uphold this code. Please report unacceptable behavior to mailto:leo@ldmd.mx[leo@ldmd.mx].

=== Help and Improvements

Feel free to email me at the email provided above or tweet me at my https://ldmd.mx/twitter[@thelmariscal].

=== Bug Report

Before reporting check that you are in the latest version of this library.

Check if this bug has already been reported in the https://github.com/lmariscal/nimgl/issues[Issues]. If it hasn't
feel free to submit an issue that is as clear as possible and try to add examples on how to replicate this exact problem.

=== Pull Requests

We heavily appreciate pull requests, feel free to make any pull request but also feel free to discuss it beforehand to
avoid rejecting your work.

If you have more than 3 commits please rebase to squash some of them down. If you don't know how to squash
https://youtu.be/2E23I9PzplM[here] is a tutorial. Also follow the https://nim-lang.org/docs/nep1.html[Nim Styleguide],
except the 80 characters limit and the whitespace for better code readability, almost all editors have extensions to
automatically align code.

=== How the project is organized

TODO.

=== Instructions

Before starting to modify the code please install the Editor Config extension for your Editor of preference, you can
find them at http://editorconfig.org/.

. Fork the Repo
. Clone the repo with `git clone --recursive -j8 git@github.com:lmariscal/nimgl.git`
. Run `nimble build`
. Modify, commit and push.
. Create Pull Request with squashed commits and changelog.
. Remember to make the Pull Request to the `develop` branch

=== License Note

All your your contributions are permanent and you agree them to fall under the MIT License. +
For more information check the link:LICENSE[LICENSE].
