FROM nimlang/nim

USER root

RUN apt-get update
RUN apt-get -y install freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev git xorg-dev curl
